feat(component-labels): add 2 new optional properties
milantenk/ngx-interactive-paycard pull request #7
Opened 2020-10-16 21:20 UTC by Villanuevand

```
[cardLabels]="{}"
 [formLabels]="{}"
```

Are 2 new properties to add the capability to modify: 
- Card Labels
- Form Labels

If those 2 options are not specified we are providing values by default.

2020-10-17 09:06 UTC, milantenk requested changes
Good job, the PR looks really great! 
I had only some minor comments regarding code conventions and the READMEs. Could you please check them?

2020-10-17 09:06 UTC, milantenk commented on projects/ngx-interactive-paycard-demo/src/app/app.component.ts
> +import {CardLabel, FormLabel} from 'ngx-interactive-paycard-lib';
Could you please add a whitespace before `CardLabel` and after `Formlabel` to follow the conventions. (If you use VS Code, `ALT+SHIFT+F` does it with the default settings.)

2020-10-17 09:06 UTC, milantenk commented on projects/ngx-interactive-paycard-lib/src/lib/card/card.component.ts
> +
Could you please add a whitespace before and after `CardLabel` to follow the conventions. And please remove the unnecessary line.

2020-10-17 09:06 UTC, milantenk commented on projects/ngx-interactive-paycard-lib/src/lib/shared/default-component-labels.ts
> +
Could you please remove this empty line?

2020-10-19 14:57 UTC, Villanuevand commented
@milantenk 
Sure I'll do...  Im glad you like it!

2020-10-20 05:29 UTC, merged